"""Add favorite table

Revision ID: 0b10bd19fc4e
Revises: 82c956358d26
Create Date: 2025-11-10 20:05:42.643361

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b10bd19fc4e"
down_revision: str | None = "82c956358d26"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorite",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_favorite_account_id"), "favorite", ["account_id"], unique=False)
    op.create_index(op.f("ix_favorite_id"), "favorite", ["id"], unique=False)
    op.create_index(op.f("ix_favorite_job_id"), "favorite", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_favorite_job_id"), table_name="favorite")
    op.drop_index(op.f("ix_favorite_id"), table_name="favorite")
    op.drop_index(op.f("ix_favorite_account_id"), table_name="favorite")
    op.drop_table("favorite")
    # ### end Alembic commands ###
