"""refactor domain models

Revision ID: a0932c60c76f
Revises: ecd2da078037
Create Date: 2025-11-09 12:01:05.107677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0932c60c76f'
down_revision: Union[str, None] = 'ecd2da078037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DRONER', 'EMPLOYER', name='accounttype').create(op.get_bind())
    op.add_column('account', sa.Column('account_type', postgresql.ENUM('DRONER', 'EMPLOYER', name='accounttype', create_type=False), nullable=True))
    op.add_column('account', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('account', 'account_type_id')
    op.drop_column('account', 'account_status_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('account_status_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('account', sa.Column('account_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('account', 'is_active')
    op.drop_column('account', 'account_type')
    sa.Enum('DRONER', 'EMPLOYER', name='accounttype').drop(op.get_bind())
    # ### end Alembic commands ###
