"""add application table

Revision ID: b3a7d2e9c4f1
Revises: 82c956358d26
Create Date: 2025-11-10 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b3a7d2e9c4f1"
down_revision: Union[str, None] = "82c956358d26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "PENDING",
        "ACCEPTED",
        "REJECTED",
        "WITHDRAWN",
        name="applicationstatus",
    ).create(op.get_bind())
    op.create_table(
        "application",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "REJECTED",
                "WITHDRAWN",
                name="applicationstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"]),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_application_id"), "application", ["id"], unique=False)
    op.create_index(
        op.f("ix_application_job_id"), "application", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_application_account_id"), "application", ["account_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_application_account_id"), table_name="application")
    op.drop_index(op.f("ix_application_job_id"), table_name="application")
    op.drop_index(op.f("ix_application_id"), table_name="application")
    op.drop_table("application")
    sa.Enum(
        "PENDING",
        "ACCEPTED",
        "REJECTED",
        "WITHDRAWN",
        name="applicationstatus",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
