"""Add Job dates constraints

Revision ID: d5b1b680fec4
Revises: bcc103cda934
Create Date: 2025-11-14 11:58:21.083223

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5b1b680fec4"
down_revision: Union[str, None] = "bcc103cda934"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint("chk_budget_non_negative", "job", "budget >= 0")
    op.create_check_constraint("chk_end_date_after_start_date", "job", "end_date >= start_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chk_end_date_after_start_date", "job", type_="check")
    op.drop_constraint("chk_budget_non_negative", "job", type_="check")
    # ### end Alembic commands ###
