"""Add account table

Revision ID: ecd2da078037
Revises: d88b0c5aaacb
Create Date: 2025-11-07 19:50:35.306062

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecd2da078037"
down_revision: str | None = "d88b0c5aaacb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("account_type_id", sa.Integer(), nullable=False),
        sa.Column("account_status_type_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_id"), "account", ["id"], unique=False)
    op.create_index(op.f("ix_account_user_id"), "account", ["user_id"], unique=False)
    op.drop_constraint(op.f("job_account_id_fkey"), "job", type_="foreignkey")
    op.create_foreign_key(None, "job", "account", ["account_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "job", type_="foreignkey")  # type: ignore[arg-type]
    op.create_foreign_key(op.f("job_account_id_fkey"), "job", "user", ["account_id"], ["id"])
    op.drop_index(op.f("ix_account_user_id"), table_name="account")
    op.drop_index(op.f("ix_account_id"), table_name="account")
    op.drop_table("account")
    # ### end Alembic commands ###
